/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial Black32.c                                       *
* Font:        Arial Black                                           *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
* Pixel index of character 0x7C (124) at 2/13 set to 0               *
* Pixel index of character 0x7C (124) at 3/13 set to 0               *
* Pixel index of character 0x7C (124) at 4/13 set to 0               *
* Pixel index of character 0x7C (124) at 2/24 set to 0               *
* Pixel index of character 0x7C (124) at 3/24 set to 0               *
* Pixel index of character 0x7C (124) at 4/24 set to 0               *
* Pixel index of character 0x7C (124) at 2/25 set to 0               *
* Pixel index of character 0x7C (124) at 3/25 set to 0               *
* Pixel index of character 0x7C (124) at 4/25 set to 0               *
* Pixel index of character 0x7C (124) at 2/26 set to 0               *
* Pixel index of character 0x7C (124) at 3/26 set to 0               *
* Pixel index of character 0x7C (124) at 4/26 set to 0               *
* Pixel index of character 0x7C (124) at 2/27 set to 0               *
* Pixel index of character 0x7C (124) at 3/27 set to 0               *
* Pixel index of character 0x7C (124) at 4/27 set to 0               *
* Pixel index of character 0x7C (124) at 2/28 set to 0               *
* Pixel index of character 0x7C (124) at 3/28 set to 0               *
* Pixel index of character 0x7C (124) at 4/28 set to 0               *
* Pixel index of character 0x7C (124) at 2/29 set to 0               *
* Pixel index of character 0x7C (124) at 3/29 set to 0               *
* Pixel index of character 0x7C (124) at 4/29 set to 0               *
* Pixel index of character 0x7C (124) at 2/12 set to 0               *
* Pixel index of character 0x7C (124) at 3/12 set to 0               *
* Pixel index of character 0x7C (124) at 4/12 set to 0               *
* Pixel index of character 0x7C (124) at 4/11 set to 0               *
* Pixel index of character 0x7C (124) at 3/11 set to 0               *
* Pixel index of character 0x7C (124) at 2/11 set to 0               *
* Pixel index of character 0x7C (124) at 4/10 set to 0               *
* Pixel index of character 0x7C (124) at 3/10 set to 0               *
* Pixel index of character 0x7C (124) at 2/10 set to 0               *
* Pixel index of character 0x7C (124) at 2/9 set to 0                *
* Pixel index of character 0x7C (124) at 3/9 set to 0                *
* Pixel index of character 0x7C (124) at 4/9 set to 0                *
* Pixel index of character 0x7C (124) at 4/8 set to 0                *
* Pixel index of character 0x7C (124) at 3/8 set to 0                *
* Pixel index of character 0x7C (124) at 2/8 set to 0                *
* Pixel index of character 0x9B (155) at 3/13 set to 1               *
* Pixel index of character 0x9B (155) at 2/13 set to 1               *
* Pixel index of character 0x9B (155) at 1/13 set to 1               *
* Pixel index of character 0x9B (155) at 1/12 set to 1               *
* Pixel index of character 0x9B (155) at 2/12 set to 1               *
* Pixel index of character 0x9B (155) at 7/17 set to 1               *
* Pixel index of character 0x9B (155) at 1/15 set to 1               *
* Pixel index of character 0x9B (155) at 1/16 set to 1               *
* Pixel index of character 0x9B (155) at 1/17 set to 1               *
* Pixel index of character 0x9B (155) at 1/18 set to 1               *
* Pixel index of character 0x9B (155) at 1/19 set to 1               *
* Pixel index of character 0x9B (155) at 1/20 set to 1               *
* Pixel index of character 0x9B (155) at 1/21 set to 1               *
* Pixel index of character 0x9B (155) at 1/22 set to 1               *
* Pixel index of character 0x9B (155) at 2/20 set to 1               *
* Pixel index of character 0x9B (155) at 2/19 set to 1               *
* Pixel index of character 0x9B (155) at 2/18 set to 1               *
* Pixel index of character 0x9B (155) at 2/17 set to 1               *
* Pixel index of character 0x9B (155) at 2/16 set to 1               *
* Pixel index of character 0x9B (155) at 3/18 set to 1               *
* Pixel index of character 0x9B (155) at 3/23 set to 0               *
* Pixel index of character 0x9B (155) at 4/22 set to 0               *
* Pixel index of character 0x9B (155) at 5/21 set to 0               *
* Pixel index of character 0x9B (155) at 6/20 set to 0               *
* Pixel index of character 0x9B (155) at 5/22 set to 0               *
* Pixel index of character 0x9B (155) at 4/23 set to 0               *
* Pixel index of character 0x6C (108) at 5/7 set to 1                *
* Pixel index of character 0x6C (108) at 5/6 set to 1                *
* Pixel index of character 0x6C (108) at 5/5 set to 1                *
* Pixel index of character 0x6C (108) at 5/4 set to 1                *
* Pixel index of character 0x6C (108) at 5/3 set to 1                *
* Pixel index of character 0x6C (108) at 5/2 set to 1                *
* Pixel index of character 0x6C (108) at 5/1 set to 1                *
* Pixel index of character 0x6C (108) at 5/0 set to 1                *
* Pixel index of character 0x6C (108) at 4/0 set to 1                *
* Pixel index of character 0x6C (108) at 4/1 set to 1                *
* Pixel index of character 0x6C (108) at 4/2 set to 1                *
* Pixel index of character 0x6C (108) at 4/3 set to 1                *
* Pixel index of character 0x6C (108) at 4/4 set to 1                *
* Pixel index of character 0x6C (108) at 4/5 set to 1                *
* Pixel index of character 0x6C (108) at 4/6 set to 1                *
* Pixel index of character 0x6C (108) at 4/7 set to 1                *
* Pixel index of character 0x6C (108) at 3/7 set to 1                *
* Pixel index of character 0x6C (108) at 3/6 set to 1                *
* Pixel index of character 0x6C (108) at 3/5 set to 1                *
* Pixel index of character 0x6C (108) at 3/4 set to 1                *
* Pixel index of character 0x6C (108) at 3/3 set to 1                *
* Pixel index of character 0x6C (108) at 3/2 set to 1                *
* Pixel index of character 0x6C (108) at 3/1 set to 1                *
* Pixel index of character 0x6C (108) at 3/0 set to 1                *
* Pixel index of character 0x6C (108) at 2/0 set to 1                *
* Pixel index of character 0x6C (108) at 2/1 set to 1                *
* Pixel index of character 0x6C (108) at 2/2 set to 1                *
* Pixel index of character 0x6C (108) at 2/3 set to 1                *
* Pixel index of character 0x6C (108) at 2/4 set to 1                *
* Pixel index of character 0x6C (108) at 2/5 set to 1                *
* Pixel index of character 0x6C (108) at 2/6 set to 1                *
* Pixel index of character 0x6C (108) at 2/7 set to 1                *
* Pixel index of character 0x6C (108) at 1/7 set to 1                *
* Pixel index of character 0x6C (108) at 1/6 set to 1                *
* Pixel index of character 0x6C (108) at 1/5 set to 1                *
* Pixel index of character 0x6C (108) at 1/4 set to 1                *
* Pixel index of character 0x6C (108) at 1/3 set to 1                *
* Pixel index of character 0x6C (108) at 1/2 set to 1                *
* Pixel index of character 0x6C (108) at 1/1 set to 1                *
* Pixel index of character 0x6C (108) at 1/0 set to 1                *
* Pixel index of character 0x6C (108) at 5/25 set to 1               *
* Pixel index of character 0x6C (108) at 5/26 set to 1               *
* Pixel index of character 0x6C (108) at 5/27 set to 1               *
* Pixel index of character 0x6C (108) at 5/28 set to 1               *
* Pixel index of character 0x6C (108) at 5/29 set to 1               *
* Pixel index of character 0x6C (108) at 5/30 set to 1               *
* Pixel index of character 0x6C (108) at 5/31 set to 1               *
* Pixel index of character 0x6C (108) at 4/31 set to 1               *
* Pixel index of character 0x6C (108) at 4/30 set to 1               *
* Pixel index of character 0x6C (108) at 4/29 set to 1               *
* Pixel index of character 0x6C (108) at 4/28 set to 1               *
* Pixel index of character 0x6C (108) at 4/27 set to 1               *
* Pixel index of character 0x6C (108) at 4/26 set to 1               *
* Pixel index of character 0x6C (108) at 4/25 set to 1               *
* Pixel index of character 0x6C (108) at 3/25 set to 1               *
* Pixel index of character 0x6C (108) at 3/26 set to 1               *
* Pixel index of character 0x6C (108) at 3/27 set to 1               *
* Pixel index of character 0x6C (108) at 3/28 set to 1               *
* Pixel index of character 0x6C (108) at 3/29 set to 1               *
* Pixel index of character 0x6C (108) at 3/30 set to 1               *
* Pixel index of character 0x6C (108) at 3/31 set to 1               *
* Pixel index of character 0x6C (108) at 2/31 set to 1               *
* Pixel index of character 0x6C (108) at 2/30 set to 1               *
* Pixel index of character 0x6C (108) at 2/29 set to 1               *
* Pixel index of character 0x6C (108) at 2/28 set to 1               *
* Pixel index of character 0x6C (108) at 2/27 set to 1               *
* Pixel index of character 0x6C (108) at 2/26 set to 1               *
* Pixel index of character 0x6C (108) at 2/25 set to 1               *
* Pixel index of character 0x6C (108) at 1/26 set to 1               *
* Pixel index of character 0x6C (108) at 1/27 set to 1               *
* Pixel index of character 0x6C (108) at 1/25 set to 1               *
* Pixel index of character 0x6C (108) at 1/28 set to 1               *
* Pixel index of character 0x6C (108) at 1/29 set to 1               *
* Pixel index of character 0x6C (108) at 1/30 set to 1               *
* Pixel index of character 0x6C (108) at 1/31 set to 1               *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Pixel index of character 0xD (13) at 0/0 set to 1                  *
* Pixel index of character 0xD (13) at 0/31 set to 1                 *
* Pixel index of character 0xD (13) at 1/30 set to 1                 *
* Pixel index of character 0xD (13) at 2/29 set to 1                 *
* Pixel index of character 0xD (13) at 3/28 set to 1                 *
* Pixel index of character 0xD (13) at 4/27 set to 1                 *
* Pixel index of character 0xD (13) at 5/26 set to 1                 *
* Pixel index of character 0xD (13) at 6/25 set to 1                 *
* Pixel index of character 0xD (13) at 7/24 set to 1                 *
* Pixel index of character 0xD (13) at 8/23 set to 1                 *
* Pixel index of character 0xD (13) at 9/22 set to 1                 *
* Pixel index of character 0xD (13) at 10/21 set to 1                *
* Pixel index of character 0xD (13) at 11/20 set to 1                *
* Pixel index of character 0xD (13) at 12/19 set to 1                *
* Pixel index of character 0xD (13) at 13/18 set to 1                *
* Pixel index of character 0xD (13) at 14/17 set to 1                *
* Pixel index of character 0xD (13) at 15/16 set to 1                *
* Pixel index of character 0xD (13) at 16/15 set to 1                *
* Pixel index of character 0xD (13) at 1/1 set to 1                  *
* Pixel index of character 0xD (13) at 2/2 set to 1                  *
* Pixel index of character 0xD (13) at 3/3 set to 1                  *
* Pixel index of character 0xD (13) at 4/4 set to 1                  *
* Pixel index of character 0xD (13) at 5/5 set to 1                  *
* Pixel index of character 0xD (13) at 6/6 set to 1                  *
* Pixel index of character 0xD (13) at 7/7 set to 1                  *
* Pixel index of character 0xD (13) at 8/8 set to 1                  *
* Pixel index of character 0xD (13) at 9/9 set to 1                  *
* Pixel index of character 0xD (13) at 10/10 set to 1                *
* Pixel index of character 0xD (13) at 11/11 set to 1                *
* Pixel index of character 0xD (13) at 12/12 set to 1                *
* Pixel index of character 0xD (13) at 13/13 set to 1                *
* Pixel index of character 0xD (13) at 14/14 set to 1                *
* Pixel index of character 0xD (13) at 15/15 set to 1                *
* Pixel index of character 0xD (13) at 16/15 set to 0                *
* Pixel index of character 0xD (13) at 14/16 set to 1                *
* Pixel index of character 0xD (13) at 14/15 set to 1                *
* Pixel index of character 0xD (13) at 13/15 set to 1                *
* Pixel index of character 0xD (13) at 13/14 set to 1                *
* Pixel index of character 0xD (13) at 13/16 set to 1                *
* Pixel index of character 0xD (13) at 13/17 set to 1                *
* Pixel index of character 0xD (13) at 12/17 set to 1                *
* Pixel index of character 0xD (13) at 12/16 set to 1                *
* Pixel index of character 0xD (13) at 12/15 set to 1                *
* Pixel index of character 0xD (13) at 12/14 set to 1                *
* Pixel index of character 0xD (13) at 12/13 set to 1                *
* Pixel index of character 0xD (13) at 12/18 set to 1                *
* Pixel index of character 0xD (13) at 11/19 set to 1                *
* Pixel index of character 0xD (13) at 10/20 set to 1                *
* Pixel index of character 0xD (13) at 9/21 set to 1                 *
* Pixel index of character 0xD (13) at 8/22 set to 1                 *
* Pixel index of character 0xD (13) at 7/23 set to 1                 *
* Pixel index of character 0xD (13) at 6/24 set to 1                 *
* Pixel index of character 0xD (13) at 5/25 set to 1                 *
* Pixel index of character 0xD (13) at 4/26 set to 1                 *
* Pixel index of character 0xD (13) at 3/27 set to 1                 *
* Pixel index of character 0xD (13) at 2/28 set to 1                 *
* Pixel index of character 0xD (13) at 1/29 set to 1                 *
* Pixel index of character 0xD (13) at 0/30 set to 1                 *
* Pixel index of character 0xD (13) at 0/29 set to 1                 *
* Pixel index of character 0xD (13) at 0/28 set to 1                 *
* Pixel index of character 0xD (13) at 0/27 set to 1                 *
* Pixel index of character 0xD (13) at 1/28 set to 1                 *
* Pixel index of character 0xD (13) at 1/27 set to 1                 *
* Pixel index of character 0xD (13) at 2/27 set to 1                 *
* Pixel index of character 0xD (13) at 2/26 set to 1                 *
* Pixel index of character 0xD (13) at 3/26 set to 1                 *
* Pixel index of character 0xD (13) at 4/25 set to 1                 *
* Pixel index of character 0xD (13) at 5/24 set to 1                 *
* Pixel index of character 0xD (13) at 6/23 set to 1                 *
* Pixel index of character 0xD (13) at 7/22 set to 1                 *
* Pixel index of character 0xD (13) at 8/21 set to 1                 *
* Pixel index of character 0xD (13) at 9/20 set to 1                 *
* Pixel index of character 0xD (13) at 10/19 set to 1                *
* Pixel index of character 0xD (13) at 11/18 set to 1                *
* Pixel index of character 0xD (13) at 11/16 set to 1                *
* Pixel index of character 0xD (13) at 11/15 set to 1                *
* Pixel index of character 0xD (13) at 11/13 set to 1                *
* Pixel index of character 0xD (13) at 11/12 set to 1                *
* Pixel index of character 0xD (13) at 11/14 set to 1                *
* Pixel index of character 0xD (13) at 11/17 set to 1                *
* Pixel index of character 0xD (13) at 10/18 set to 1                *
* Pixel index of character 0xD (13) at 10/17 set to 1                *
* Pixel index of character 0xD (13) at 10/16 set to 1                *
* Pixel index of character 0xD (13) at 10/15 set to 1                *
* Pixel index of character 0xD (13) at 10/14 set to 1                *
* Pixel index of character 0xD (13) at 10/13 set to 1                *
* Pixel index of character 0xD (13) at 10/12 set to 1                *
* Pixel index of character 0xD (13) at 10/11 set to 1                *
* Pixel index of character 0xD (13) at 9/11 set to 1                 *
* Pixel index of character 0xD (13) at 9/10 set to 1                 *
* Pixel index of character 0xD (13) at 9/12 set to 1                 *
* Pixel index of character 0xD (13) at 9/13 set to 1                 *
* Pixel index of character 0xD (13) at 9/14 set to 1                 *
* Pixel index of character 0xD (13) at 9/15 set to 1                 *
* Pixel index of character 0xD (13) at 9/16 set to 1                 *
* Pixel index of character 0xD (13) at 9/17 set to 1                 *
* Pixel index of character 0xD (13) at 9/18 set to 1                 *
* Pixel index of character 0xD (13) at 9/19 set to 1                 *
* Pixel index of character 0xD (13) at 8/20 set to 1                 *
* Pixel index of character 0xD (13) at 8/19 set to 1                 *
* Pixel index of character 0xD (13) at 8/18 set to 1                 *
* Pixel index of character 0xD (13) at 8/17 set to 1                 *
* Pixel index of character 0xD (13) at 8/16 set to 1                 *
* Pixel index of character 0xD (13) at 8/15 set to 1                 *
* Pixel index of character 0xD (13) at 8/14 set to 1                 *
* Pixel index of character 0xD (13) at 8/13 set to 1                 *
* Pixel index of character 0xD (13) at 8/12 set to 1                 *
* Pixel index of character 0xD (13) at 8/11 set to 1                 *
* Pixel index of character 0xD (13) at 8/10 set to 1                 *
* Pixel index of character 0xD (13) at 8/9 set to 1                  *
* Pixel index of character 0xD (13) at 7/8 set to 1                  *
* Pixel index of character 0xD (13) at 7/9 set to 1                  *
* Pixel index of character 0xD (13) at 7/10 set to 1                 *
* Pixel index of character 0xD (13) at 7/11 set to 1                 *
* Pixel index of character 0xD (13) at 7/12 set to 1                 *
* Pixel index of character 0xD (13) at 7/13 set to 1                 *
* Pixel index of character 0xD (13) at 7/14 set to 1                 *
* Pixel index of character 0xD (13) at 7/15 set to 1                 *
* Pixel index of character 0xD (13) at 7/17 set to 1                 *
* Pixel index of character 0xD (13) at 7/18 set to 1                 *
* Pixel index of character 0xD (13) at 7/16 set to 1                 *
* Pixel index of character 0xD (13) at 7/20 set to 1                 *
* Pixel index of character 0xD (13) at 7/19 set to 1                 *
* Pixel index of character 0xD (13) at 7/21 set to 1                 *
* Pixel index of character 0xD (13) at 6/22 set to 1                 *
* Pixel index of character 0xD (13) at 6/21 set to 1                 *
* Pixel index of character 0xD (13) at 6/20 set to 1                 *
* Pixel index of character 0xD (13) at 6/19 set to 1                 *
* Pixel index of character 0xD (13) at 6/18 set to 1                 *
* Pixel index of character 0xD (13) at 6/17 set to 1                 *
* Pixel index of character 0xD (13) at 6/16 set to 1                 *
* Pixel index of character 0xD (13) at 6/15 set to 1                 *
* Pixel index of character 0xD (13) at 6/14 set to 1                 *
* Pixel index of character 0xD (13) at 6/13 set to 1                 *
* Pixel index of character 0xD (13) at 6/12 set to 1                 *
* Pixel index of character 0xD (13) at 6/11 set to 1                 *
* Pixel index of character 0xD (13) at 6/10 set to 1                 *
* Pixel index of character 0xD (13) at 6/9 set to 1                  *
* Pixel index of character 0xD (13) at 6/8 set to 1                  *
* Pixel index of character 0xD (13) at 6/7 set to 1                  *
* Pixel index of character 0xD (13) at 5/7 set to 1                  *
* Pixel index of character 0xD (13) at 5/6 set to 1                  *
* Pixel index of character 0xD (13) at 5/8 set to 1                  *
* Pixel index of character 0xD (13) at 5/10 set to 1                 *
* Pixel index of character 0xD (13) at 5/9 set to 1                  *
* Pixel index of character 0xD (13) at 5/11 set to 1                 *
* Pixel index of character 0xD (13) at 5/12 set to 1                 *
* Pixel index of character 0xD (13) at 5/13 set to 1                 *
* Pixel index of character 0xD (13) at 5/14 set to 1                 *
* Pixel index of character 0xD (13) at 5/15 set to 1                 *
* Pixel index of character 0xD (13) at 5/16 set to 1                 *
* Pixel index of character 0xD (13) at 5/17 set to 1                 *
* Pixel index of character 0xD (13) at 5/18 set to 1                 *
* Pixel index of character 0xD (13) at 5/19 set to 1                 *
* Pixel index of character 0xD (13) at 5/20 set to 1                 *
* Pixel index of character 0xD (13) at 5/21 set to 1                 *
* Pixel index of character 0xD (13) at 5/22 set to 1                 *
* Pixel index of character 0xD (13) at 5/23 set to 1                 *
* Pixel index of character 0xD (13) at 4/23 set to 1                 *
* Pixel index of character 0xD (13) at 4/24 set to 1                 *
* Pixel index of character 0xD (13) at 3/24 set to 1                 *
* Pixel index of character 0xD (13) at 3/25 set to 1                 *
* Pixel index of character 0xD (13) at 2/25 set to 1                 *
* Pixel index of character 0xD (13) at 1/26 set to 1                 *
* Pixel index of character 0xD (13) at 0/26 set to 1                 *
* Pixel index of character 0xD (13) at 0/25 set to 1                 *
* Pixel index of character 0xD (13) at 1/25 set to 1                 *
* Pixel index of character 0xD (13) at 1/24 set to 1                 *
* Pixel index of character 0xD (13) at 2/24 set to 1                 *
* Pixel index of character 0xD (13) at 2/23 set to 1                 *
* Pixel index of character 0xD (13) at 4/22 set to 1                 *
* Pixel index of character 0xD (13) at 4/21 set to 1                 *
* Pixel index of character 0xD (13) at 4/20 set to 1                 *
* Pixel index of character 0xD (13) at 4/19 set to 1                 *
* Pixel index of character 0xD (13) at 4/18 set to 1                 *
* Pixel index of character 0xD (13) at 4/17 set to 1                 *
* Pixel index of character 0xD (13) at 4/16 set to 1                 *
* Pixel index of character 0xD (13) at 4/14 set to 1                 *
* Pixel index of character 0xD (13) at 4/13 set to 1                 *
* Pixel index of character 0xD (13) at 4/11 set to 1                 *
* Pixel index of character 0xD (13) at 4/10 set to 1                 *
* Pixel index of character 0xD (13) at 4/8 set to 1                  *
* Pixel index of character 0xD (13) at 4/7 set to 1                  *
* Pixel index of character 0xD (13) at 4/6 set to 1                  *
* Pixel index of character 0xD (13) at 4/5 set to 1                  *
* Pixel index of character 0xD (13) at 4/9 set to 1                  *
* Pixel index of character 0xD (13) at 4/12 set to 1                 *
* Pixel index of character 0xD (13) at 4/15 set to 1                 *
* Pixel index of character 0xD (13) at 3/23 set to 1                 *
* Pixel index of character 0xD (13) at 3/22 set to 1                 *
* Pixel index of character 0xD (13) at 3/21 set to 1                 *
* Pixel index of character 0xD (13) at 3/20 set to 1                 *
* Pixel index of character 0xD (13) at 3/18 set to 1                 *
* Pixel index of character 0xD (13) at 3/15 set to 1                 *
* Pixel index of character 0xD (13) at 3/14 set to 1                 *
* Pixel index of character 0xD (13) at 3/13 set to 1                 *
* Pixel index of character 0xD (13) at 3/11 set to 1                 *
* Pixel index of character 0xD (13) at 3/9 set to 1                  *
* Pixel index of character 0xD (13) at 3/8 set to 1                  *
* Pixel index of character 0xD (13) at 3/6 set to 1                  *
* Pixel index of character 0xD (13) at 3/5 set to 1                  *
* Pixel index of character 0xD (13) at 3/4 set to 1                  *
* Pixel index of character 0xD (13) at 3/7 set to 1                  *
* Pixel index of character 0xD (13) at 3/10 set to 1                 *
* Pixel index of character 0xD (13) at 3/12 set to 1                 *
* Pixel index of character 0xD (13) at 3/16 set to 1                 *
* Pixel index of character 0xD (13) at 3/17 set to 1                 *
* Pixel index of character 0xD (13) at 3/19 set to 1                 *
* Pixel index of character 0xD (13) at 2/22 set to 1                 *
* Pixel index of character 0xD (13) at 2/21 set to 1                 *
* Pixel index of character 0xD (13) at 2/20 set to 1                 *
* Pixel index of character 0xD (13) at 2/19 set to 1                 *
* Pixel index of character 0xD (13) at 2/18 set to 1                 *
* Pixel index of character 0xD (13) at 2/17 set to 1                 *
* Pixel index of character 0xD (13) at 2/15 set to 1                 *
* Pixel index of character 0xD (13) at 2/13 set to 1                 *
* Pixel index of character 0xD (13) at 2/12 set to 1                 *
* Pixel index of character 0xD (13) at 2/10 set to 1                 *
* Pixel index of character 0xD (13) at 2/9 set to 1                  *
* Pixel index of character 0xD (13) at 2/8 set to 1                  *
* Pixel index of character 0xD (13) at 2/6 set to 1                  *
* Pixel index of character 0xD (13) at 2/5 set to 1                  *
* Pixel index of character 0xD (13) at 2/4 set to 1                  *
* Pixel index of character 0xD (13) at 2/3 set to 1                  *
* Pixel index of character 0xD (13) at 2/7 set to 1                  *
* Pixel index of character 0xD (13) at 2/11 set to 1                 *
* Pixel index of character 0xD (13) at 2/14 set to 1                 *
* Pixel index of character 0xD (13) at 2/16 set to 1                 *
* Pixel index of character 0xD (13) at 1/23 set to 1                 *
* Pixel index of character 0xD (13) at 1/22 set to 1                 *
* Pixel index of character 0xD (13) at 1/21 set to 1                 *
* Pixel index of character 0xD (13) at 1/20 set to 1                 *
* Pixel index of character 0xD (13) at 1/18 set to 1                 *
* Pixel index of character 0xD (13) at 1/17 set to 1                 *
* Pixel index of character 0xD (13) at 1/15 set to 1                 *
* Pixel index of character 0xD (13) at 1/14 set to 1                 *
* Pixel index of character 0xD (13) at 1/13 set to 1                 *
* Pixel index of character 0xD (13) at 1/11 set to 1                 *
* Pixel index of character 0xD (13) at 1/10 set to 1                 *
* Pixel index of character 0xD (13) at 1/9 set to 1                  *
* Pixel index of character 0xD (13) at 1/8 set to 1                  *
* Pixel index of character 0xD (13) at 1/7 set to 1                  *
* Pixel index of character 0xD (13) at 1/6 set to 1                  *
* Pixel index of character 0xD (13) at 1/5 set to 1                  *
* Pixel index of character 0xD (13) at 1/4 set to 1                  *
* Pixel index of character 0xD (13) at 1/3 set to 1                  *
* Pixel index of character 0xD (13) at 1/2 set to 1                  *
* Pixel index of character 0xD (13) at 1/12 set to 1                 *
* Pixel index of character 0xD (13) at 1/16 set to 1                 *
* Pixel index of character 0xD (13) at 1/19 set to 1                 *
* Pixel index of character 0xD (13) at 0/24 set to 1                 *
* Pixel index of character 0xD (13) at 0/23 set to 1                 *
* Pixel index of character 0xD (13) at 0/22 set to 1                 *
* Pixel index of character 0xD (13) at 0/21 set to 1                 *
* Pixel index of character 0xD (13) at 0/19 set to 1                 *
* Pixel index of character 0xD (13) at 0/16 set to 1                 *
* Pixel index of character 0xD (13) at 0/14 set to 1                 *
* Pixel index of character 0xD (13) at 0/10 set to 1                 *
* Pixel index of character 0xD (13) at 0/8 set to 1                  *
* Pixel index of character 0xD (13) at 0/6 set to 1                  *
* Pixel index of character 0xD (13) at 0/5 set to 1                  *
* Pixel index of character 0xD (13) at 0/4 set to 1                  *
* Pixel index of character 0xD (13) at 0/3 set to 1                  *
* Pixel index of character 0xD (13) at 0/2 set to 1                  *
* Pixel index of character 0xD (13) at 0/1 set to 1                  *
* Pixel index of character 0xD (13) at 0/7 set to 1                  *
* Pixel index of character 0xD (13) at 0/9 set to 1                  *
* Pixel index of character 0xD (13) at 0/11 set to 1                 *
* Pixel index of character 0xD (13) at 0/12 set to 1                 *
* Pixel index of character 0xD (13) at 0/13 set to 1                 *
* Pixel index of character 0xD (13) at 0/15 set to 1                 *
* Pixel index of character 0xD (13) at 0/17 set to 1                 *
* Pixel index of character 0xD (13) at 0/18 set to 1                 *
* Pixel index of character 0xD (13) at 0/20 set to 1                 *
* Edit/Delete/Left      at character 0xD (13)                        *
* Edit/Delete/Left      at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Right     at character 0xD (13)                        *
* Edit/Insert/Left      at character 0xD (13)                        *
* Edit/Insert/Left      at character 0xD (13)                        *
* Pixel index of character 0xD (13) at 1/1 set to 1                  *
* Pixel index of character 0xD (13) at 0/0 set to 1                  *
* Pixel index of character 0xD (13) at 0/1 set to 1                  *
* Pixel index of character 0xD (13) at 0/2 set to 1                  *
* Pixel index of character 0xD (13) at 1/2 set to 1                  *
* Pixel index of character 0xD (13) at 1/30 set to 1                 *
* Pixel index of character 0xD (13) at 0/31 set to 1                 *
* Pixel index of character 0xD (13) at 0/29 set to 1                 *
* Pixel index of character 0xD (13) at 0/28 set to 1                 *
* Pixel index of character 0xD (13) at 0/27 set to 1                 *
* Pixel index of character 0xD (13) at 0/26 set to 1                 *
* Pixel index of character 0xD (13) at 0/25 set to 1                 *
* Pixel index of character 0xD (13) at 0/23 set to 1                 *
* Pixel index of character 0xD (13) at 0/22 set to 1                 *
* Pixel index of character 0xD (13) at 0/20 set to 1                 *
* Pixel index of character 0xD (13) at 0/19 set to 1                 *
* Pixel index of character 0xD (13) at 0/17 set to 1                 *
* Pixel index of character 0xD (13) at 0/15 set to 1                 *
* Pixel index of character 0xD (13) at 0/14 set to 1                 *
* Pixel index of character 0xD (13) at 0/13 set to 1                 *
* Pixel index of character 0xD (13) at 0/12 set to 1                 *
* Pixel index of character 0xD (13) at 0/9 set to 1                  *
* Pixel index of character 0xD (13) at 0/7 set to 1                  *
* Pixel index of character 0xD (13) at 0/6 set to 1                  *
* Pixel index of character 0xD (13) at 0/5 set to 1                  *
* Pixel index of character 0xD (13) at 0/3 set to 1                  *
* Pixel index of character 0xD (13) at 1/3 set to 1                  *
* Pixel index of character 0xD (13) at 1/5 set to 1                  *
* Pixel index of character 0xD (13) at 1/7 set to 1                  *
* Pixel index of character 0xD (13) at 1/11 set to 1                 *
* Pixel index of character 0xD (13) at 1/13 set to 1                 *
* Pixel index of character 0xD (13) at 1/16 set to 1                 *
* Pixel index of character 0xD (13) at 1/18 set to 1                 *
* Pixel index of character 0xD (13) at 1/20 set to 1                 *
* Pixel index of character 0xD (13) at 1/22 set to 1                 *
* Pixel index of character 0xD (13) at 1/24 set to 1                 *
* Pixel index of character 0xD (13) at 1/26 set to 1                 *
* Pixel index of character 0xD (13) at 1/28 set to 1                 *
* Pixel index of character 0xD (13) at 0/30 set to 1                 *
* Pixel index of character 0xD (13) at 1/29 set to 1                 *
* Pixel index of character 0xD (13) at 1/27 set to 1                 *
* Pixel index of character 0xD (13) at 0/24 set to 1                 *
* Pixel index of character 0xD (13) at 1/25 set to 1                 *
* Pixel index of character 0xD (13) at 1/23 set to 1                 *
* Pixel index of character 0xD (13) at 1/21 set to 1                 *
* Pixel index of character 0xD (13) at 1/19 set to 1                 *
* Pixel index of character 0xD (13) at 1/17 set to 1                 *
* Pixel index of character 0xD (13) at 0/16 set to 1                 *
* Pixel index of character 0xD (13) at 1/14 set to 1                 *
* Pixel index of character 0xD (13) at 1/10 set to 1                 *
* Pixel index of character 0xD (13) at 1/9 set to 1                  *
* Pixel index of character 0xD (13) at 1/8 set to 1                  *
* Pixel index of character 0xD (13) at 1/6 set to 1                  *
* Pixel index of character 0xD (13) at 1/4 set to 1                  *
* Pixel index of character 0xD (13) at 0/4 set to 1                  *
* Pixel index of character 0xD (13) at 0/10 set to 1                 *
* Pixel index of character 0xD (13) at 0/11 set to 1                 *
* Pixel index of character 0xD (13) at 1/12 set to 1                 *
* Pixel index of character 0xD (13) at 1/15 set to 1                 *
* Pixel index of character 0xD (13) at 0/18 set to 1                 *
* Pixel index of character 0xD (13) at 0/21 set to 1                 *
* Pixel index of character 0xD (13) at 0/8 set to 1                  *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Edit/Delete/Right     at character 0xD (13)                        *
* Character enabled:   0xD (13)                                      *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Delete/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Edit/Insert/Right     at character 0xC (12)                        *
* Pixel index of character 0xC (12) at 15/0 set to 1                 *
* Pixel index of character 0xC (12) at 14/1 set to 1                 *
* Pixel index of character 0xC (12) at 13/2 set to 1                 *
* Pixel index of character 0xC (12) at 12/3 set to 1                 *
* Pixel index of character 0xC (12) at 11/4 set to 1                 *
* Pixel index of character 0xC (12) at 10/5 set to 1                 *
* Pixel index of character 0xC (12) at 9/6 set to 1                  *
* Pixel index of character 0xC (12) at 8/7 set to 1                  *
* Pixel index of character 0xC (12) at 7/8 set to 1                  *
* Pixel index of character 0xC (12) at 6/9 set to 1                  *
* Pixel index of character 0xC (12) at 5/10 set to 1                 *
* Pixel index of character 0xC (12) at 4/11 set to 1                 *
* Pixel index of character 0xC (12) at 3/12 set to 1                 *
* Pixel index of character 0xC (12) at 2/13 set to 1                 *
* Pixel index of character 0xC (12) at 1/14 set to 1                 *
* Pixel index of character 0xC (12) at 0/15 set to 1                 *
* Pixel index of character 0xC (12) at 15/31 set to 1                *
* Pixel index of character 0xC (12) at 14/30 set to 1                *
* Pixel index of character 0xC (12) at 13/29 set to 1                *
* Pixel index of character 0xC (12) at 12/28 set to 1                *
* Pixel index of character 0xC (12) at 11/27 set to 1                *
* Pixel index of character 0xC (12) at 10/26 set to 1                *
* Pixel index of character 0xC (12) at 9/25 set to 1                 *
* Pixel index of character 0xC (12) at 8/24 set to 1                 *
* Pixel index of character 0xC (12) at 7/23 set to 1                 *
* Pixel index of character 0xC (12) at 6/22 set to 1                 *
* Pixel index of character 0xC (12) at 5/21 set to 1                 *
* Pixel index of character 0xC (12) at 4/20 set to 1                 *
* Pixel index of character 0xC (12) at 3/19 set to 1                 *
* Pixel index of character 0xC (12) at 2/18 set to 1                 *
* Pixel index of character 0xC (12) at 1/17 set to 1                 *
* Pixel index of character 0xC (12) at 0/16 set to 1                 *
* Pixel index of character 0xC (12) at 15/30 set to 1                *
* Pixel index of character 0xC (12) at 15/29 set to 1                *
* Pixel index of character 0xC (12) at 15/27 set to 1                *
* Pixel index of character 0xC (12) at 15/26 set to 1                *
* Pixel index of character 0xC (12) at 14/25 set to 1                *
* Pixel index of character 0xC (12) at 12/21 set to 1                *
* Pixel index of character 0xC (12) at 9/17 set to 1                 *
* Pixel index of character 0xC (12) at 6/16 set to 1                 *
* Pixel index of character 0xC (12) at 4/15 set to 1                 *
* Pixel index of character 0xC (12) at 8/11 set to 1                 *
* Pixel index of character 0xC (12) at 13/10 set to 1                *
* Pixel index of character 0xC (12) at 12/19 set to 1                *
* Pixel index of character 0xC (12) at 11/22 set to 1                *
* Pixel index of character 0xC (12) at 6/19 set to 1                 *
* Pixel index of character 0xC (12) at 3/15 set to 1                 *
* Pixel index of character 0xC (12) at 2/15 set to 1                 *
* Pixel index of character 0xC (12) at 2/16 set to 1                 *
* Pixel index of character 0xC (12) at 12/11 set to 1                *
* Pixel index of character 0xC (12) at 12/7 set to 1                 *
* Pixel index of character 0xC (12) at 15/3 set to 1                 *
* Pixel index of character 0xC (12) at 13/9 set to 1                 *
* Pixel index of character 0xC (12) at 13/16 set to 1                *
* Pixel index of character 0xC (12) at 13/21 set to 1                *
* Pixel index of character 0xC (12) at 7/22 set to 1                 *
* Pixel index of character 0xC (12) at 4/19 set to 1                 *
* Pixel index of character 0xC (12) at 2/17 set to 1                 *
* Pixel index of character 0xC (12) at 1/16 set to 1                 *
* Pixel index of character 0xC (12) at 1/15 set to 1                 *
* Pixel index of character 0xC (12) at 4/14 set to 1                 *
* Pixel index of character 0xC (12) at 7/13 set to 1                 *
* Pixel index of character 0xC (12) at 12/17 set to 1                *
* Pixel index of character 0xC (12) at 12/26 set to 1                *
* Pixel index of character 0xC (12) at 13/28 set to 1                *
* Pixel index of character 0xC (12) at 14/29 set to 1                *
* Pixel index of character 0xC (12) at 15/28 set to 1                *
* Pixel index of character 0xC (12) at 14/28 set to 1                *
* Pixel index of character 0xC (12) at 14/27 set to 1                *
* Pixel index of character 0xC (12) at 12/27 set to 1                *
* Pixel index of character 0xC (12) at 13/27 set to 1                *
* Pixel index of character 0xC (12) at 13/26 set to 1                *
* Pixel index of character 0xC (12) at 14/26 set to 1                *
* Pixel index of character 0xC (12) at 15/24 set to 1                *
* Pixel index of character 0xC (12) at 15/23 set to 1                *
* Pixel index of character 0xC (12) at 15/22 set to 1                *
* Pixel index of character 0xC (12) at 15/21 set to 1                *
* Pixel index of character 0xC (12) at 15/25 set to 1                *
* Pixel index of character 0xC (12) at 15/20 set to 1                *
* Pixel index of character 0xC (12) at 15/19 set to 1                *
* Pixel index of character 0xC (12) at 15/18 set to 1                *
* Pixel index of character 0xC (12) at 15/17 set to 1                *
* Pixel index of character 0xC (12) at 15/16 set to 1                *
* Pixel index of character 0xC (12) at 15/15 set to 1                *
* Pixel index of character 0xC (12) at 15/14 set to 1                *
* Pixel index of character 0xC (12) at 15/13 set to 1                *
* Pixel index of character 0xC (12) at 15/12 set to 1                *
* Pixel index of character 0xC (12) at 15/11 set to 1                *
* Pixel index of character 0xC (12) at 15/10 set to 1                *
* Pixel index of character 0xC (12) at 15/9 set to 1                 *
* Pixel index of character 0xC (12) at 15/8 set to 1                 *
* Pixel index of character 0xC (12) at 15/7 set to 1                 *
* Pixel index of character 0xC (12) at 15/6 set to 1                 *
* Pixel index of character 0xC (12) at 15/5 set to 1                 *
* Pixel index of character 0xC (12) at 15/4 set to 1                 *
* Pixel index of character 0xC (12) at 15/2 set to 1                 *
* Pixel index of character 0xC (12) at 15/1 set to 1                 *
* Pixel index of character 0xC (12) at 14/2 set to 1                 *
* Pixel index of character 0xC (12) at 14/3 set to 1                 *
* Pixel index of character 0xC (12) at 14/5 set to 1                 *
* Pixel index of character 0xC (12) at 14/7 set to 1                 *
* Pixel index of character 0xC (12) at 14/12 set to 1                *
* Pixel index of character 0xC (12) at 14/14 set to 1                *
* Pixel index of character 0xC (12) at 14/16 set to 1                *
* Pixel index of character 0xC (12) at 14/19 set to 1                *
* Pixel index of character 0xC (12) at 14/21 set to 1                *
* Pixel index of character 0xC (12) at 14/23 set to 1                *
* Pixel index of character 0xC (12) at 14/24 set to 1                *
* Pixel index of character 0xC (12) at 14/22 set to 1                *
* Pixel index of character 0xC (12) at 14/18 set to 1                *
* Pixel index of character 0xC (12) at 14/17 set to 1                *
* Pixel index of character 0xC (12) at 14/11 set to 1                *
* Pixel index of character 0xC (12) at 14/9 set to 1                 *
* Pixel index of character 0xC (12) at 14/6 set to 1                 *
* Pixel index of character 0xC (12) at 14/4 set to 1                 *
* Pixel index of character 0xC (12) at 14/8 set to 1                 *
* Pixel index of character 0xC (12) at 14/10 set to 1                *
* Pixel index of character 0xC (12) at 14/13 set to 1                *
* Pixel index of character 0xC (12) at 14/15 set to 1                *
* Pixel index of character 0xC (12) at 14/20 set to 1                *
* Pixel index of character 0xC (12) at 13/20 set to 1                *
* Pixel index of character 0xC (12) at 13/19 set to 1                *
* Pixel index of character 0xC (12) at 13/18 set to 1                *
* Pixel index of character 0xC (12) at 13/17 set to 1                *
* Pixel index of character 0xC (12) at 13/15 set to 1                *
* Pixel index of character 0xC (12) at 13/14 set to 1                *
* Pixel index of character 0xC (12) at 13/13 set to 1                *
* Pixel index of character 0xC (12) at 13/12 set to 1                *
* Pixel index of character 0xC (12) at 13/11 set to 1                *
* Pixel index of character 0xC (12) at 13/8 set to 1                 *
* Pixel index of character 0xC (12) at 13/7 set to 1                 *
* Pixel index of character 0xC (12) at 13/6 set to 1                 *
* Pixel index of character 0xC (12) at 13/5 set to 1                 *
* Pixel index of character 0xC (12) at 13/4 set to 1                 *
* Pixel index of character 0xC (12) at 13/3 set to 1                 *
* Pixel index of character 0xC (12) at 13/25 set to 1                *
* Pixel index of character 0xC (12) at 13/24 set to 1                *
* Pixel index of character 0xC (12) at 13/23 set to 1                *
* Pixel index of character 0xC (12) at 13/22 set to 1                *
* Pixel index of character 0xC (12) at 12/22 set to 1                *
* Pixel index of character 0xC (12) at 12/23 set to 1                *
* Pixel index of character 0xC (12) at 12/24 set to 1                *
* Pixel index of character 0xC (12) at 12/25 set to 1                *
* Pixel index of character 0xC (12) at 11/26 set to 1                *
* Pixel index of character 0xC (12) at 11/25 set to 1                *
* Pixel index of character 0xC (12) at 11/24 set to 1                *
* Pixel index of character 0xC (12) at 11/23 set to 1                *
* Pixel index of character 0xC (12) at 10/25 set to 1                *
* Pixel index of character 0xC (12) at 10/24 set to 1                *
* Pixel index of character 0xC (12) at 10/22 set to 1                *
* Pixel index of character 0xC (12) at 10/21 set to 1                *
* Pixel index of character 0xC (12) at 10/20 set to 1                *
* Pixel index of character 0xC (12) at 10/19 set to 1                *
* Pixel index of character 0xC (12) at 10/17 set to 1                *
* Pixel index of character 0xC (12) at 10/16 set to 1                *
* Pixel index of character 0xC (12) at 10/14 set to 1                *
* Pixel index of character 0xC (12) at 10/12 set to 1                *
* Pixel index of character 0xC (12) at 10/9 set to 1                 *
* Pixel index of character 0xC (12) at 10/7 set to 1                 *
* Pixel index of character 0xC (12) at 10/6 set to 1                 *
* Pixel index of character 0xC (12) at 10/8 set to 1                 *
* Pixel index of character 0xC (12) at 10/10 set to 1                *
* Pixel index of character 0xC (12) at 10/11 set to 1                *
* Pixel index of character 0xC (12) at 10/13 set to 1                *
* Pixel index of character 0xC (12) at 10/15 set to 1                *
* Pixel index of character 0xC (12) at 10/18 set to 1                *
* Pixel index of character 0xC (12) at 10/23 set to 1                *
* Pixel index of character 0xC (12) at 9/24 set to 1                 *
* Pixel index of character 0xC (12) at 8/23 set to 1                 *
* Pixel index of character 0xC (12) at 8/22 set to 1                 *
* Pixel index of character 0xC (12) at 6/21 set to 1                 *
* Pixel index of character 0xC (12) at 5/20 set to 1                 *
* Pixel index of character 0xC (12) at 3/18 set to 1                 *
* Pixel index of character 0xC (12) at 3/17 set to 1                 *
* Pixel index of character 0xC (12) at 3/16 set to 1                 *
* Pixel index of character 0xC (12) at 4/16 set to 1                 *
* Pixel index of character 0xC (12) at 5/19 set to 1                 *
* Pixel index of character 0xC (12) at 7/21 set to 1                 *
* Pixel index of character 0xC (12) at 9/22 set to 1                 *
* Pixel index of character 0xC (12) at 9/23 set to 1                 *
* Pixel index of character 0xC (12) at 9/21 set to 1                 *
* Pixel index of character 0xC (12) at 9/18 set to 1                 *
* Pixel index of character 0xC (12) at 9/19 set to 1                 *
* Pixel index of character 0xC (12) at 9/20 set to 1                 *
* Pixel index of character 0xC (12) at 8/21 set to 1                 *
* Pixel index of character 0xC (12) at 8/20 set to 1                 *
* Pixel index of character 0xC (12) at 8/19 set to 1                 *
* Pixel index of character 0xC (12) at 7/20 set to 1                 *
* Pixel index of character 0xC (12) at 6/20 set to 1                 *
* Pixel index of character 0xC (12) at 7/19 set to 1                 *
* Pixel index of character 0xC (12) at 7/18 set to 1                 *
* Pixel index of character 0xC (12) at 6/18 set to 1                 *
* Pixel index of character 0xC (12) at 5/18 set to 1                 *
* Pixel index of character 0xC (12) at 4/18 set to 1                 *
* Pixel index of character 0xC (12) at 4/17 set to 1                 *
* Pixel index of character 0xC (12) at 5/17 set to 1                 *
* Pixel index of character 0xC (12) at 8/18 set to 1                 *
* Pixel index of character 0xC (12) at 8/17 set to 1                 *
* Pixel index of character 0xC (12) at 7/17 set to 1                 *
* Pixel index of character 0xC (12) at 6/17 set to 1                 *
* Pixel index of character 0xC (12) at 7/16 set to 1                 *
* Pixel index of character 0xC (12) at 8/16 set to 1                 *
* Pixel index of character 0xC (12) at 9/16 set to 1                 *
* Pixel index of character 0xC (12) at 9/15 set to 1                 *
* Pixel index of character 0xC (12) at 9/14 set to 1                 *
* Pixel index of character 0xC (12) at 9/12 set to 1                 *
* Pixel index of character 0xC (12) at 9/8 set to 1                  *
* Pixel index of character 0xC (12) at 9/7 set to 1                  *
* Pixel index of character 0xC (12) at 9/9 set to 1                  *
* Pixel index of character 0xC (12) at 9/11 set to 1                 *
* Pixel index of character 0xC (12) at 9/13 set to 1                 *
* Pixel index of character 0xC (12) at 9/10 set to 1                 *
* Pixel index of character 0xC (12) at 12/4 set to 1                 *
* Pixel index of character 0xC (12) at 12/5 set to 1                 *
* Pixel index of character 0xC (12) at 11/5 set to 1                 *
* Pixel index of character 0xC (12) at 11/8 set to 1                 *
* Pixel index of character 0xC (12) at 11/10 set to 1                *
* Pixel index of character 0xC (12) at 11/11 set to 1                *
* Pixel index of character 0xC (12) at 11/14 set to 1                *
* Pixel index of character 0xC (12) at 11/16 set to 1                *
* Pixel index of character 0xC (12) at 11/18 set to 1                *
* Pixel index of character 0xC (12) at 11/21 set to 1                *
* Pixel index of character 0xC (12) at 12/20 set to 1                *
* Pixel index of character 0xC (12) at 11/20 set to 1                *
* Pixel index of character 0xC (12) at 12/18 set to 1                *
* Pixel index of character 0xC (12) at 11/19 set to 1                *
* Pixel index of character 0xC (12) at 11/17 set to 1                *
* Pixel index of character 0xC (12) at 12/16 set to 1                *
* Pixel index of character 0xC (12) at 12/15 set to 1                *
* Pixel index of character 0xC (12) at 12/14 set to 1                *
* Pixel index of character 0xC (12) at 12/13 set to 1                *
* Pixel index of character 0xC (12) at 12/12 set to 1                *
* Pixel index of character 0xC (12) at 11/12 set to 1                *
* Pixel index of character 0xC (12) at 11/15 set to 1                *
* Pixel index of character 0xC (12) at 11/13 set to 1                *
* Pixel index of character 0xC (12) at 12/10 set to 1                *
* Pixel index of character 0xC (12) at 12/9 set to 1                 *
* Pixel index of character 0xC (12) at 12/8 set to 1                 *
* Pixel index of character 0xC (12) at 11/9 set to 1                 *
* Pixel index of character 0xC (12) at 11/7 set to 1                 *
* Pixel index of character 0xC (12) at 11/6 set to 1                 *
* Pixel index of character 0xC (12) at 12/6 set to 1                 *
* Pixel index of character 0xC (12) at 8/15 set to 1                 *
* Pixel index of character 0xC (12) at 8/14 set to 1                 *
* Pixel index of character 0xC (12) at 8/12 set to 1                 *
* Pixel index of character 0xC (12) at 8/13 set to 1                 *
* Pixel index of character 0xC (12) at 8/10 set to 1                 *
* Pixel index of character 0xC (12) at 8/9 set to 1                  *
* Pixel index of character 0xC (12) at 7/9 set to 1                  *
* Pixel index of character 0xC (12) at 7/10 set to 1                 *
* Pixel index of character 0xC (12) at 7/11 set to 1                 *
* Pixel index of character 0xC (12) at 7/12 set to 1                 *
* Pixel index of character 0xC (12) at 7/14 set to 1                 *
* Pixel index of character 0xC (12) at 7/15 set to 1                 *
* Pixel index of character 0xC (12) at 6/15 set to 1                 *
* Pixel index of character 0xC (12) at 5/15 set to 1                 *
* Pixel index of character 0xC (12) at 5/16 set to 1                 *
* Pixel index of character 0xC (12) at 6/14 set to 1                 *
* Pixel index of character 0xC (12) at 6/13 set to 1                 *
* Pixel index of character 0xC (12) at 6/12 set to 1                 *
* Pixel index of character 0xC (12) at 6/11 set to 1                 *
* Pixel index of character 0xC (12) at 6/10 set to 1                 *
* Pixel index of character 0xC (12) at 5/11 set to 1                 *
* Pixel index of character 0xC (12) at 5/12 set to 1                 *
* Pixel index of character 0xC (12) at 5/13 set to 1                 *
* Pixel index of character 0xC (12) at 5/14 set to 1                 *
* Pixel index of character 0xC (12) at 4/13 set to 1                 *
* Pixel index of character 0xC (12) at 4/12 set to 1                 *
* Pixel index of character 0xC (12) at 3/13 set to 1                 *
* Pixel index of character 0xC (12) at 2/14 set to 1                 *
* Pixel index of character 0xC (12) at 3/14 set to 1                 *
* Pixel index of character 0xC (12) at 8/8 set to 1                  *
* Character disabled:  0x4 (4)                                       *
* Character disabled:  0x5 (5)                                       *
* Character disabled:  0x6 (6)                                       *
* Character disabled:  0x7 (7)                                       *
* Character disabled:  0x8 (8)                                       *
* Character disabled:  0x9 (9)                                       *
* Character disabled:  0xA (10)                                      *
* Character disabled:  0xB (11)                                      *
* Character disabled:  0xE (14)                                      *
* Character enabled:   0xE (14)                                      *
* Character disabled:  0x0 (0)                                       *
* Character disabled:  0x1 (1)                                       *
* Character disabled:  0x2 (2)                                       *
* Character disabled:  0x3 (3)                                       *
* Character disabled:  0xE (14)                                      *
* Character enabled:   0xE (14)                                      *
* Character disabled:  0xE (14)                                      *
* Character disabled:  0xF (15)                                      *
* Character disabled:  0x20 (32)                                     *
* Character disabled:  0x21 (33)                                     *
* Character disabled:  0x22 (34)                                     *
* Character disabled:  0x23 (35)                                     *
* Character disabled:  0x24 (36)                                     *
* Character disabled:  0x25 (37)                                     *
* Character disabled:  0x26 (38)                                     *
* Character disabled:  0x6B (107)                                    *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x6D (109)                                    *
* Character enabled:   0x6D (109)                                    *
* Character disabled:  0x6D (109)                                    *
* Character disabled:  0x7D (125)                                    *
* Character disabled:  0x7C (124)                                    *
* Character disabled:  0x7B (123)                                    *
* Character disabled:  0x27 (39)                                     *
* Character disabled:  0x28 (40)                                     *
* Character disabled:  0x29 (41)                                     *
* Character disabled:  0x2A (42)                                     *
* Character disabled:  0x2B (43)                                     *
* Character disabled:  0x2C (44)                                     *
* Character disabled:  0x2D (45)                                     *
* Character disabled:  0x2E (46)                                     *
* Character disabled:  0x2F (47)                                     *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3A (58)                                     *
* Character disabled:  0x39 (57)                                     *
* Character disabled:  0x38 (56)                                     *
* Character disabled:  0x37 (55)                                     *
* Character disabled:  0x36 (54)                                     *
* Character disabled:  0x35 (53)                                     *
* Character disabled:  0x34 (52)                                     *
* Character disabled:  0x33 (51)                                     *
* Character disabled:  0x32 (50)                                     *
* Character disabled:  0x31 (49)                                     *
* Character disabled:  0x30 (48)                                     *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x41 (65)                                     *
* Character disabled:  0x42 (66)                                     *
* Character disabled:  0x43 (67)                                     *
* Character disabled:  0x44 (68)                                     *
* Character disabled:  0x45 (69)                                     *
* Character disabled:  0x46 (70)                                     *
* Character disabled:  0x47 (71)                                     *
* Character disabled:  0x48 (72)                                     *
* Character disabled:  0x49 (73)                                     *
* Character disabled:  0x4A (74)                                     *
* Character disabled:  0x4B (75)                                     *
* Character disabled:  0x4C (76)                                     *
* Character disabled:  0x4D (77)                                     *
* Character disabled:  0x4E (78)                                     *
* Character disabled:  0x4F (79)                                     *
* Character disabled:  0x5F (95)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x6E (110)                                    *
* Character disabled:  0x6F (111)                                    *
* Character disabled:  0x7F (127)                                    *
* Character disabled:  0x7E (126)                                    *
* Character disabled:  0x6A (106)                                    *
* Character disabled:  0x5A (90)                                     *
* Character disabled:  0x69 (105)                                    *
* Character disabled:  0x79 (121)                                    *
* Character disabled:  0x7A (122)                                    *
* Character disabled:  0x59 (89)                                     *
* Character disabled:  0x78 (120)                                    *
* Character disabled:  0x68 (104)                                    *
* Character disabled:  0x58 (88)                                     *
* Character disabled:  0x77 (119)                                    *
* Character disabled:  0x67 (103)                                    *
* Character disabled:  0x57 (87)                                     *
* Character disabled:  0x76 (118)                                    *
* Character disabled:  0x66 (102)                                    *
* Character disabled:  0x56 (86)                                     *
* Character disabled:  0x75 (117)                                    *
* Character disabled:  0x65 (101)                                    *
* Character disabled:  0x55 (85)                                     *
* Character disabled:  0x64 (100)                                    *
* Character disabled:  0x74 (116)                                    *
* Character disabled:  0x54 (84)                                     *
* Character disabled:  0x73 (115)                                    *
* Character disabled:  0x63 (99)                                     *
* Character disabled:  0x53 (83)                                     *
* Character disabled:  0x72 (114)                                    *
* Character disabled:  0x62 (98)                                     *
* Character disabled:  0x52 (82)                                     *
* Character disabled:  0x61 (97)                                     *
* Character disabled:  0x71 (113)                                    *
* Character disabled:  0x51 (81)                                     *
* Character disabled:  0x70 (112)                                    *
* Character disabled:  0x60 (96)                                     *
* Character disabled:  0x50 (80)                                     *
* Character disabled:  0x91 (145)                                    *
* Character disabled:  0x92 (146)                                    *
* Character disabled:  0x93 (147)                                    *
* Character disabled:  0x94 (148)                                    *
* Character disabled:  0x95 (149)                                    *
* Character disabled:  0x96 (150)                                    *
* Character disabled:  0x97 (151)                                    *
* Character disabled:  0x98 (152)                                    *
* Character disabled:  0x99 (153)                                    *
* Character disabled:  0x9A (154)                                    *
* Character disabled:  0x9B (155)                                    *
* Character disabled:  0x9C (156)                                    *
* Character disabled:  0x9E (158)                                    *
* Character disabled:  0xAF (175)                                    *
* Character disabled:  0x9F (159)                                    *
* Character disabled:  0xAE (174)                                    *
* Character disabled:  0xAD (173)                                    *
* Character disabled:  0xAC (172)                                    *
* Character disabled:  0xAB (171)                                    *
* Character disabled:  0xAA (170)                                    *
* Character disabled:  0xA9 (169)                                    *
* Character disabled:  0xA8 (168)                                    *
* Character disabled:  0xA7 (167)                                    *
* Character disabled:  0xA6 (166)                                    *
* Character disabled:  0xA5 (165)                                    *
* Character enabled:   0xA5 (165)                                    *
* Character disabled:  0xA4 (164)                                    *
* Character disabled:  0xA3 (163)                                    *
* Character disabled:  0xA2 (162)                                    *
* Character disabled:  0xA0 (160)                                    *
* Character disabled:  0xA1 (161)                                    *
* Character disabled:  0xA5 (165)                                    *
* Character disabled:  0xB1 (177)                                    *
* Character disabled:  0xB2 (178)                                    *
* Character disabled:  0xB0 (176)                                    *
* Character disabled:  0xB3 (179)                                    *
* Character disabled:  0xB4 (180)                                    *
* Character disabled:  0xB5 (181)                                    *
* Character disabled:  0xB6 (182)                                    *
* Character disabled:  0xB7 (183)                                    *
* Character disabled:  0xB8 (184)                                    *
* Character disabled:  0xB9 (185)                                    *
* Character disabled:  0xBA (186)                                    *
* Character disabled:  0xBB (187)                                    *
* Character disabled:  0xBC (188)                                    *
* Character disabled:  0xBD (189)                                    *
* Character disabled:  0xBE (190)                                    *
* Character disabled:  0xBF (191)                                    *
* Character disabled:  0xC0 (192)                                    *
* Character disabled:  0xC1 (193)                                    *
* Character disabled:  0xC2 (194)                                    *
* Character disabled:  0xC3 (195)                                    *
* Character disabled:  0xC4 (196)                                    *
* Character disabled:  0xC5 (197)                                    *
* Character disabled:  0xC6 (198)                                    *
* Character disabled:  0xC7 (199)                                    *
* Character disabled:  0xC8 (200)                                    *
* Character disabled:  0xC9 (201)                                    *
* Character disabled:  0xCA (202)                                    *
* Character disabled:  0xCB (203)                                    *
* Character enabled:   0xCB (203)                                    *
* Character disabled:  0xCC (204)                                    *
* Character disabled:  0xCE (206)                                    *
* Character disabled:  0xCB (203)                                    *
* Character disabled:  0xCD (205)                                    *
* Character disabled:  0xCF (207)                                    *
* Character disabled:  0xDF (223)                                    *
* Character disabled:  0xEF (239)                                    *
* Character disabled:  0xFF (255)                                    *
* Character disabled:  0xFE (254)                                    *
* Character disabled:  0xEE (238)                                    *
* Character disabled:  0xDE (222)                                    *
* Character disabled:  0xDD (221)                                    *
* Character disabled:  0xED (237)                                    *
* Character disabled:  0xFD (253)                                    *
* Character disabled:  0xFC (252)                                    *
* Character disabled:  0xEC (236)                                    *
* Character disabled:  0xDC (220)                                    *
* Character disabled:  0xEB (235)                                    *
* Character disabled:  0xFB (251)                                    *
* Character disabled:  0xDB (219)                                    *
* Character disabled:  0xFA (250)                                    *
* Character disabled:  0xEA (234)                                    *
* Character disabled:  0xDA (218)                                    *
* Character disabled:  0xF9 (249)                                    *
* Character disabled:  0xE9 (233)                                    *
* Character disabled:  0xD9 (217)                                    *
* Character disabled:  0xF8 (248)                                    *
* Character disabled:  0xE8 (232)                                    *
* Character disabled:  0xD8 (216)                                    *
* Character disabled:  0xF7 (247)                                    *
* Character disabled:  0xE7 (231)                                    *
* Character disabled:  0xD7 (215)                                    *
* Character disabled:  0xF6 (246)                                    *
* Character disabled:  0xE6 (230)                                    *
* Character disabled:  0xD6 (214)                                    *
* Character disabled:  0xF5 (245)                                    *
* Character disabled:  0xE5 (229)                                    *
* Character disabled:  0xD5 (213)                                    *
* Character disabled:  0xF4 (244)                                    *
* Character disabled:  0xE4 (228)                                    *
* Character disabled:  0xD4 (212)                                    *
* Character disabled:  0xF3 (243)                                    *
* Character disabled:  0xE3 (227)                                    *
* Character disabled:  0xD3 (211)                                    *
* Character disabled:  0xE2 (226)                                    *
* Character disabled:  0xD2 (210)                                    *
* Character disabled:  0xF2 (242)                                    *
* Character disabled:  0xF1 (241)                                    *
* Character disabled:  0xE1 (225)                                    *
* Character disabled:  0xD1 (209)                                    *
* Character disabled:  0xF0 (240)                                    *
* Character disabled:  0xE0 (224)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArialBlack32;

GUI_CONST_STORAGE unsigned char acGUI_FontArialBlack32_000C[ 64] = { /* code 000C */
  ________,_______X,
  ________,______XX,
  ________,_____XXX,
  ________,____XXXX,
  ________,___XXXXX,
  ________,__XXXXXX,
  ________,_XXXXXXX,
  ________,XXXXXXXX,
  _______X,XXXXXXXX,
  ______XX,XXXXXXXX,
  _____XXX,XXXXXXXX,
  ____XXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,
  ____XXXX,XXXXXXXX,
  _____XXX,XXXXXXXX,
  ______XX,XXXXXXXX,
  _______X,XXXXXXXX,
  ________,XXXXXXXX,
  ________,_XXXXXXX,
  ________,__XXXXXX,
  ________,___XXXXX,
  ________,____XXXX,
  ________,_____XXX,
  ________,______XX,
  ________,_______X};

GUI_CONST_STORAGE unsigned char acGUI_FontArialBlack32_000D[ 64] = { /* code 000D */
  X_______,________,
  XX______,________,
  XXX_____,________,
  XXXX____,________,
  XXXXX___,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XXXXX___,________,
  XXXX____,________,
  XXX_____,________,
  XX______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontArialBlack32_006C[ 32] = { /* code 006C */
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontArialBlack32_00D0[ 96] = { /* code 00D0 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXX_,___XXXXX,________,
  __XXXXX_,___XXXXX,X_______,
  __XXXXX_,____XXXX,X_______,
  XXXXXXXX,XX__XXXX,X_______,
  XXXXXXXX,XX__XXXX,X_______,
  __XXXXX_,____XXXX,X_______,
  __XXXXX_,____XXXX,X_______,
  __XXXXX_,____XXXX,X_______,
  __XXXXX_,___XXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontArialBlack32_CharInfo[4] = {
   {  16,  16,  2, acGUI_FontArialBlack32_000C } /* code 000C */
  ,{  16,  16,  2, acGUI_FontArialBlack32_000D } /* code 000D */
  ,{   8,   8,  1, acGUI_FontArialBlack32_006C } /* code 006C */
  ,{  18,  18,  3, acGUI_FontArialBlack32_00D0 } /* code 00D0 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontArialBlack32_Prop3 = {
   0x00D0 /* first character */
  ,0x00D0 /* last character  */
  ,&GUI_FontArialBlack32_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontArialBlack32_Prop2 = {
   0x006C /* first character */
  ,0x006C /* last character  */
  ,&GUI_FontArialBlack32_CharInfo[  2] /* address of first character */
  ,&GUI_FontArialBlack32_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontArialBlack32_Prop1 = {
   0x000C /* first character */
  ,0x000D /* last character  */
  ,&GUI_FontArialBlack32_CharInfo[  0] /* address of first character */
  ,&GUI_FontArialBlack32_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArialBlack32 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArialBlack32_Prop1}
  ,25 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

